-- Migration: Add scene breakdown feature
-- Date: 2025-01-05
-- Description: Add columns to ideas table and create scene_breakdown_history table

-- Add scene breakdown columns to ideas table
ALTER TABLE ideas
  ADD COLUMN IF NOT EXISTS scene_breakdown TEXT,
  ADD COLUMN IF NOT EXISTS scene_breakdown_generated_at TIMESTAMPTZ;

-- Create scene breakdown history table
CREATE TABLE IF NOT EXISTS scene_breakdown_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idea_id BIGINT NOT NULL REFERENCES ideas(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users,
  content TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW()),
  version INTEGER NOT NULL
);

-- Create index for efficient history queries
CREATE INDEX IF NOT EXISTS idx_scene_breakdown_history_idea_id
  ON scene_breakdown_history(idea_id, generated_at DESC);

-- Enable Row Level Security
ALTER TABLE scene_breakdown_history ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for scene_breakdown_history
CREATE POLICY "Users can view their own scene breakdown history"
  ON scene_breakdown_history
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own history"
  ON scene_breakdown_history
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own history"
  ON scene_breakdown_history
  FOR DELETE
  USING (auth.uid() = user_id);

-- Ensure Realtime is enabled for ideas table (for scene breakdown sync)
-- Run this in Supabase dashboard: Database > Replication > Enable for ideas table
-- ALTER PUBLICATION supabase_realtime ADD TABLE ideas;
