-- Drop old function and trigger if they exist
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

-- Create user_coins table
CREATE TABLE IF NOT EXISTS user_coins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL UNIQUE,
  coins INTEGER DEFAULT 10 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS user_coins_user_id_idx ON user_coins(user_id);
CREATE INDEX IF NOT EXISTS user_coins_coins_idx ON user_coins(coins);

-- Enable Row Level Security
ALTER TABLE user_coins ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view their own coins" ON user_coins;
DROP POLICY IF EXISTS "Users can insert their own coins" ON user_coins;
DROP POLICY IF EXISTS "Users can update their own coins" ON user_coins;

-- Create policies
CREATE POLICY "Users can view their own coins" ON user_coins FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own coins" ON user_coins FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own coins" ON user_coins FOR UPDATE USING (auth.uid() = user_id);

-- Trigger to automatically update updated_at
DROP TRIGGER IF EXISTS user_coins_updated_at ON user_coins;
CREATE TRIGGER user_coins_updated_at
  BEFORE UPDATE ON user_coins
  FOR EACH ROW
  EXECUTE FUNCTION handle_updated_at();

-- Function to automatically create coin balance when user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user_coins()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.user_coins (user_id, coins)
  VALUES (NEW.id, 10)
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to create coins on signup
CREATE TRIGGER on_auth_user_coins_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user_coins();
